// api/atbats.js
// Primary: public/data/players.json (generated by mlbdata_aggregate.py from raw at-bat CSVs)
// Fallback: Baseball Savant custom leaderboard CSV — single call with all needed fields

let PLAYER_CACHE = null;
let PLAYER_CACHE_TS = 0;
const THREE_HOURS = 3 * 60 * 60 * 1000;

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET');

  try {
    const now = Date.now();
    if (PLAYER_CACHE && (now - PLAYER_CACHE_TS) < THREE_HOURS) {
      console.log('[AtBats] Cache hit —', Math.round((now - PLAYER_CACHE_TS) / 60000), 'min old');
      return res.status(200).json({ players: PLAYER_CACHE, total: PLAYER_CACHE.length, fromCache: true });
    }

    const baseUrl = process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : 'http://localhost:3000';

    let data = null;

    // 1. Try local static file (players.json committed to repo)
    try {
      const staticRes = await fetch(`${baseUrl}/data/players.json`, { headers: { 'Accept': 'application/json' } });
      if (staticRes.ok) {
        data = await staticRes.json();
        console.log('[AtBats] Loaded from static file:', data?.total, 'players');
      }
    } catch(e) { console.warn('[AtBats] Static file failed:', e.message); }

    // 2. GitHub raw fallback
    if (!data?.players?.length) {
      try {
        const ghRes = await fetch(
          'https://raw.githubusercontent.com/prsm-labs/going-yard/main/public/data/players.json',
          { headers: { 'Accept': 'application/json' } }
        );
        if (ghRes.ok) { data = await ghRes.json(); console.log('[AtBats] Loaded from GitHub:', data?.total, 'players'); }
      } catch(e) { console.warn('[AtBats] GitHub failed:', e.message); }
    }

    // 3. Savant custom leaderboard fallback
    if (!data?.players?.length) {
      console.log('[AtBats] No players.json — falling back to Savant leaderboard');
      return await savantFallback(res);
    }

    const players = data.players.map(p => normalizePlayer(p));
    const valid = players.filter(p => p.pid && p.avgEV > 0);
    PLAYER_CACHE = valid;
    PLAYER_CACHE_TS = now;
    console.log(`[AtBats] Ready: ${valid.length} players | Generated: ${data.generated || 'unknown'}`);
    res.status(200).json({ players: valid, total: valid.length, generated: data.generated });

  } catch(err) {
    console.error('[AtBats] Fatal:', err.message);
    if (PLAYER_CACHE) return res.status(200).json({ players: PLAYER_CACHE, total: PLAYER_CACHE.length, fromCache: true });
    return await savantFallback(res);
  }
}

function normalizePlayer(p) {
  return {
    pid:          p.pid,
    team:         p.team          || '—',
    hand:         p.hand          || 'R',
    pos:          p.pos           || '',
    avgEV:        p.avgEV         || 0,
    maxEV:        p.maxEV         || 0,
    barrel:       p.barrel        || 0,
    hardHit:      p.hardHit       || 0,
    sweetSpot:    p.sweetSpot     || 0,
    launchAngle:  p.launchAngle   || 0,
    flyBall:      p.flyBall       || 0,
    pullPct:      p.pullPct       || p.pullAir || 0,
    pullAir:      p.pullAir       || p.pullPct || 0,
    pulledBarrel: p.pulledBarrel  || 0,
    almostHRPct:  p.almostHR      || 0,
    oSwing:       p.chasePct      || p.oSwing  || 0,
    zContact:     p.zContact      || 0,
    avg:          p.avg           || 0,
    hits:         p.hits          || 0,
    hr:           p.hr            || 0,
    xbh:          p.xbh           || 0,
    bb:           p.bb            || 0,
    k:            p.k             || 0,
    rbi:          p.rbi           || 0,
    bbPct:        p.bbPct         || 0,
    kPct:         p.kPct          || 0,
    totalBases:   p.totalBases    || 0,
    abPerHR:      p.abPerHR       || 99,
    pa:           p.pa            || 0,
    ab:           p.ab            || 0,
    bip:          p.bip           || 0,
    stolenBases:  p.stolenBases   || 0,
    xwoba:        p.xwoba         || 0,
    xba:          p.xba           || 0,
    xslg:         p.xslg          || 0,
    daysSinceHR:  p.daysSinceHR !== undefined ? p.daysSinceHR : null,
    lastHRDate:   p.lastHRDate    || null,
    careerHR:     p.careerHR      || p.hr || 0,
    vsRHP:        p.vsRHP         || null,
    vsLHP:        p.vsLHP         || null,
    pitchSplits:  p.pitchSplits   || {},
    windows:      p.windows       || {},
  };
}

async function savantFallback(res) {
  try {
    const hdrs = {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
      'Accept': 'text/csv,*/*',
      'Referer': 'https://baseballsavant.mlb.com/',
    };
    const year = '2026';

    // Single comprehensive call — custom leaderboard with all needed fields
    const SAVANT_URL = `https://baseballsavant.mlb.com/leaderboard/custom?year=${year}&type=batter&filter=&min=5` +
      `&selections=ab%2Cpa%2Chome_run%2Cstrikeout%2Cwalk%2Ck_percent%2Cbb_percent%2Cbatting_avg%2C` +
      `b_rbi%2Cb_total_bases%2Cxba%2Cxslg%2Cwoba%2Cxwoba%2C` +
      `exit_velocity_avg%2Claunch_angle_avg%2Csweet_spot_percent%2C` +
      `barrel%2Cbarrel_batted_rate%2Chard_hit_percent%2C` +
      `oz_swing_percent%2Ciz_contact_percent%2Cwhiff_percent%2Cswing_percent%2C` +
      `pull_percent%2Cstraightaway_percent%2Copposite_percent%2C` +
      `flyballs_percent%2Cflyballs%2Cgroundballs_percent%2Clinedrives_percent` +
      `&chart=false&sort=exit_velocity_avg&sortDir=desc&csv=true`;

    const csvRes = await fetch(SAVANT_URL, { headers: hdrs });
    const csvText = csvRes.ok ? await csvRes.text() : '';

    const parseCSV = (csv) => {
      if (!csv || csv.length < 50 || csv.startsWith('<')) return [];
      const lines = csv.trim().split('\n');
      const hdrow = lines[0].split(',').map(h => h.replace(/"/g,'').trim());
      return lines.slice(1).filter(l => l.trim()).map(line => {
        const vals = []; let cur = '', inQ = false;
        for (const ch of line) {
          if (ch === '"') { inQ = !inQ; }
          else if (ch === ',' && !inQ) { vals.push(cur.trim()); cur = ''; }
          else cur += ch;
        }
        vals.push(cur.trim());
        const o = {};
        hdrow.forEach((h, i) => { o[h] = (vals[i] || '').replace(/^"|"$/g, '').trim(); });
        return o;
      });
    };

    const pf = (v, cap = 999) => { const n = parseFloat(v); return isNaN(n) ? 0 : Math.min(n, cap); };

    const getName = (r) => {
      // Savant custom leaderboard uses "last_name, first_name" in player_name column
      const name = r.player_name || r['last_name, first_name'] || '';
      if (name.includes(',')) {
        const [last, ...first] = name.split(',');
        return `${first.join(',').trim()} ${last.trim()}`;
      }
      return name;
    };

    const rows = parseCSV(csvText).filter(r => r.player_id);
    console.log(`[AtBats] Savant fallback: ${rows.length} rows`);

    const players = rows.map(r => ({
      pid:         parseInt(r.player_id),
      team:        r.team_name_abbrev || r.team || '—',
      hand:        'R',
      pos:         '',
      name:        getName(r),
      // Exit velo / contact
      avgEV:       pf(r.exit_velocity_avg, 115),
      launchAngle: pf(r.launch_angle_avg),
      sweetSpot:   pf(r.sweet_spot_percent, 60),
      // Barrel
      barrel:      pf(r.barrel_batted_rate || r.barrel, 25),
      // Hard hit
      hardHit:     pf(r.hard_hit_percent, 80),
      // Pull / fly ball
      pullAir:     pf(r.pull_percent, 70),
      pullPct:     pf(r.pull_percent, 70),
      flyBall:     pf(r.flyballs_percent, 60),
      // xStats
      xwoba:       pf(r.xwoba || r.est_woba, 0.7),
      xba:         pf(r.xba || r.est_ba, 0.5),
      xslg:        pf(r.xslg || r.est_slg, 1.5),
      // Traditional
      avg:         pf(r.batting_avg, 0.5),
      pa:          parseInt(r.pa || 0),
      ab:          parseInt(r.ab || 0),
      hr:          parseInt(r.home_run || 0),
      rbi:         parseInt(r.b_rbi || 0),
      totalBases:  parseInt(r.b_total_bases || 0),
      bbPct:       pf(r.bb_percent, 30),
      kPct:        pf(r.k_percent, 50),
      // Discipline
      oSwing:      pf(r.oz_swing_percent, 60),
      zContact:    pf(r.iz_contact_percent, 100),
      whiffPct:    pf(r.whiff_percent, 60),
      // Defaults
      maxEV:0, pulledBarrel:0, almostHRPct:0, hits:0, xbh:0, bb:0, k:0,
      abPerHR:99, bip:0, stolenBases:0, daysSinceHR:null, lastHRDate:null,
      careerHR:0, vsRHP:null, vsLHP:null, pitchSplits:{}, windows:{},
    })).filter(p => p.avgEV > 0 || p.xwoba > 0);

    res.status(200).json({ players, total: players.length, fallback: true });
  } catch(e) {
    console.error('[AtBats] Savant fallback error:', e.message);
    res.status(500).json({ error: e.message, players: [] });
  }
}
