// api/ball-carry.js — live in-game "dead ball / juiced ball" tracker
//
import { readFileSync } from 'fs';
import { join } from 'path';
//
// Physics basis: holding Exit Velocity and Launch Angle fixed, a batted
// ball's carry distance should be predictable. If actual distance
// deviates significantly from that EV/LA-implied expected distance,
// the ball itself is the most likely explanation — not the swing.
//
// Deliberately does NOT use temperature or wind in the DEAD/JUICED
// classification — weather changes throughout a game and is noisy at
// single-game granularity (see CLAUDE.md ball carry research,
// 2026-07-22). Elevation IS accounted for, via PARK_CARRY_BASELINE
// below (each park's own seasonal mean deviation, subtracted before
// classifying) — this is what stops a high-altitude park like Coors
// from reading as "juiced" on every single game purely from altitude.
//
// Direction (added 2026-07-22): also corrects for batted-ball direction
// (Pull/Center/Oppo). Validated against the full 2026 AB log: Center
// contact carries ~14-17ft farther than Pull or Oppo at the same EV+LA
// (pure backspin vs. sidespin bleed-off from bat-ball collision angle)
// — a real, physically-explicable effect. Without this term, a game's
// small quality-contact sample (3-10 balls) landing unusually
// center-heavy or pull/oppo-heavy by chance produces a false
// DEAD/JUICED verdict unrelated to the ball. Confirmed this flips the
// verdict on 68/1,168 games (5.8%) in the season-to-date validation —
// a real, not cosmetic, correction. Direction is derived from
// hitData.coordinates (MLB Gameday x/y landing spot) + the batter's
// handedness (matchup.batSide.code) — both already in the live feed,
// no extra API call needed. The coordinate-to-angle conversion was
// empirically fit against 321 real batted balls cross-referenced
// against the AB log's own Spray Angle (MAE 1.08 degrees) rather than
// assumed from a public formula.
//
// CARRY_COEFFS / PARK_CARRY_BASELINE / thresholds below are a
// periodically-refreshed SNAPSHOT — the fallback used only when the
// rolling-baseline JSON (below) isn't available. They are NOT
// auto-generated by hand-editing; re-run ball_carry_tracker.py and update
// these constants if the printed reference values drift meaningfully and
// you want the fallback itself to stay current.
// Refreshed 2026-07-23 (see CLAUDE.md "Ball Carry live/offline divergence
// fix" session log): coefficients refit fresh against the current AB log
// (barely moved from the 07-22 snapshot — <0.2ft expected-distance effect
// at typical EV/LA); park baselines pulled from today's
// output/ball_carry_by_game.csv.
//
// Rolling-baseline hand-off (added 2026-07-30): ball_carry_tracker.py now
// refits this same model every pipeline run and writes its coefficients/
// park-baseline/thresholds to public/data/ball-carry-coeffs.json (via
// mlbdata_aggregate.py). loadRollingCoeffs() below reads that file at
// request time and uses it in place of the hardcoded snapshot whenever
// it's present and well-formed — so the live endpoint self-calibrates as
// the season accumulates games without needing a manual snapshot refresh.
// Falls back to the hardcoded snapshot below if the file is missing,
// unreadable, or shaped unexpectedly (never throws on a bad/missing file).
//
// Known residual (not fixable here): even with the quality-ball filter
// now matching ball_carry_tracker.py exactly (same balls get selected),
// this endpoint's real-time hitData.totalDistance runs ~1-2ft long vs.
// the finalized Statcast Hit Distance that eventually lands in the AB
// log for the SAME batted ball (confirmed 2026-07-23, cross-checked
// ball-by-ball on a real game) — an inherent live-estimate-vs-final-
// reconciled-data gap, not a bug. On a genuinely borderline game (park-
// adj deviation within ~3ft of a threshold) this can still occasionally
// disagree with the offline verdict; it will no longer disagree because
// of counting a different SET of balls, which was the dominant failure
// mode before this fix.
//
// Pitch-drag signal (added 2026-08-07) — a SEPARATE, supplementary
// diagnostic derived from pitch TRAJECTORY data (not batted-ball data),
// available from pitch 1 rather than needing MIN_BALLS_LIVE quality
// batted balls to accumulate. Validated 2026-08-06 against the full 2026
// AB log + a full-season Statcast pitch pull: different pitchers who
// threw four-seam fastballs in the SAME game show strongly correlated
// deviations from their own individual season-normal drag (split-half
// r=0.86, survives a fixed-dome control [Tampa Bay only, r=0.78] — rules
// out "it's just weather"), and correlates with this same game's real
// batted-ball carry (r=-0.23, p<0.0001). Converges almost immediately:
// the first 2 innings alone (median 23 pitches) gives essentially the
// same correlation as a full game (r=-0.237 vs r=-0.232) — the whole
// reason this is worth surfacing live rather than only offline. See
// ball_carry_tracker.py's docstring for the full writeup, including the
// honest caveat that this cannot distinguish real ball-to-ball
// manufacturing variance from Hawkeye/TrackMan calibration drift.
// Field names here use MLB's raw Gumbo convention (aX/aY/aZ/vX0/vY0/vZ0,
// capitalized) — different casing from pybaseball/Savant's lowercase
// columns the offline script uses, same physical quantities (confirmed
// live 2026-08-06 against a real in-progress game's feed/live response).
// Kept as a SEPARATE field on the response (pitchDrag: {...}), never
// blended into verdict/park_adj_deviation/z above — same V1-untouched
// discipline as every other formula addition in this project.

const SNAPSHOT_CARRY_COEFFS = [
  -365.71759, 3.86423, 20.45814, -0.00091, -0.35807, 0.02922, -13.70602, -11.8523,
];
// [intercept, EV, LA, EV^2, LA^2, EV*LA, is_pull, is_oppo] — is_pull/is_oppo
// are relative to Center (the implicit baseline when both are 0).

// Direction band: Spray Angle (post-conversion, see sprayAngleFromCoords)
// empirically centers on ~90 in the 2026 AB log (RHB mean 95.8, LHB mean
// 81.7). +/-10 deg around 90 = "Center"; outside that band, which side
// counts as "Pull" depends on batter hand.
const CENTER_LO = 80, CENTER_HI = 100;

// Home park -> that park's own seasonal mean carry deviation (ft), used
// to park/altitude-adjust before classifying. Refreshed 2026-07-23.
const SNAPSHOT_PARK_CARRY_BASELINE = {
  COL: 19.73, KC: 12.24, ATH: 11.02, TEX: 10.82, MIL: 9.19, AZ: 9.13,
  TB: 8.81, SF: 8.53, MIA: 8.12, DET: 7.15, TOR: 6.93, ATL: 6.77,
  PHI: 6.02, WSH: 5.89, STL: 4.45, LAD: 4.08, MIN: 3.65, BOS: 3.06,
  PIT: 2.97, SEA: 2.48, CHC: 2.26, BAL: 1.58, HOU: 1.37, NYY: 0.57,
  CLE: 0.57, CIN: 0.43, NYM: -1.25, SD: -1.61, CWS: -1.86, LAA: -2.44,
};

// Z-score rework (2026-07-30) — replaces the old fixed +/-11.7/-11.8ft
// thresholds with a real per-game z-score, same statistically-principled
// approach xhr-conversion.js already uses. SE of a game's own mean
// deviation = residual_sd_ft / sqrt(n) (standard SE-of-a-mean formula);
// a small-sample game now needs a much larger raw deviation to reach
// |z|>=2 than a large-sample game does — closes the small-sample false-
// positive risk flagged in the 2026-07-30 Gemini cross-check. See the
// matching comment block in ball_carry_tracker.py for the full rationale.
// SNAPSHOT_RESIDUAL_SD_FT is this endpoint's own periodically-refreshed
// fallback (refreshed 2026-07-30: real fit on 26,504 quality batted balls,
// season-to-date) — used only when the rolling JSON below isn't available.
const SNAPSHOT_RESIDUAL_SD_FT = 22.75;
const SNAPSHOT_Z_THRESHOLD    = 2.0;
const MIN_BALLS_LIVE = 3;   // fewer than this -> not enough data yet

// Reads public/data/ball-carry-coeffs.json (written fresh by
// ball_carry_tracker.py on every pipeline run) at request time. Returns
// null on any failure — missing file, unreadable, malformed shape — so
// callers can cleanly fall back to the SNAPSHOT_* constants above. No
// caching across invocations: the file is small and a cheap sync read,
// and not caching avoids a warm serverless instance silently serving a
// stale rolling baseline across day boundaries.
function loadRollingCoeffs() {
  for (const p of [
    join(process.cwd(), 'public', 'data', 'ball-carry-coeffs.json'),
    join(process.cwd(), 'going-yard', 'public', 'data', 'ball-carry-coeffs.json'),
  ]) {
    try {
      const raw = JSON.parse(readFileSync(p, 'utf-8'));
      if (
        Array.isArray(raw.coeffs) && raw.coeffs.length === 8 &&
        raw.coeffs.every(Number.isFinite) &&
        raw.park_baseline_ft && typeof raw.park_baseline_ft === 'object' &&
        Number.isFinite(raw.residual_sd_ft) && raw.residual_sd_ft > 0
      ) {
        return raw;
      }
    } catch (_) { /* try next path */ }
  }
  return null;
}

// Pitch-drag rolling hand-off (2026-08-07) — written by ball_carry_tracker.py,
// same dual-path / never-throw pattern as loadRollingCoeffs() above. Returns
// null (pitch-drag section simply omitted from the response) if missing,
// unreadable, or shaped unexpectedly.
function loadPitchDragCoeffs() {
  for (const p of [
    join(process.cwd(), 'public', 'data', 'pitch-drag-coeffs.json'),
    join(process.cwd(), 'going-yard', 'public', 'data', 'pitch-drag-coeffs.json'),
  ]) {
    try {
      const raw = JSON.parse(readFileSync(p, 'utf-8'));
      if (
        Number.isFinite(raw.population_mean_cd_proxy) &&
        Number.isFinite(raw.residual_sd) && raw.residual_sd > 0 &&
        raw.pitcher_baseline && typeof raw.pitcher_baseline === 'object'
      ) {
        return raw;
      }
    } catch (_) { /* try next path */ }
  }
  return null;
}

const MIN_FF_PITCHES_LIVE     = 3;  // per pitcher, to count that pitcher's outing tonight
const MIN_PITCHERS_LIVE       = 2;  // need >=2 distinct pitchers tonight for a game-level reading
const PITCH_DRAG_Z_THRESHOLD  = 2.0;

// Every FF (four-seam fastball) pitch's trajectory, grouped by the pitcher
// who threw it (play.matchup.pitcher.id) — confirmed live 2026-08-06 that
// this field, and playEvents[].pitchData.coordinates.{aX,aY,aZ,vX0,vY0,vZ0},
// are both populated pitch-by-pitch in real time (tested against a genuinely
// in-progress game, not just a completed one).
function collectPitchDragByPitcher(plays) {
  const byPitcher = new Map(); // pitcherId -> { sum, n }
  for (const play of plays) {
    const pitcherId = play.matchup?.pitcher?.id;
    if (!pitcherId) continue;
    for (const evt of (play.playEvents || [])) {
      if (!evt.isPitch || evt.details?.type?.code !== 'FF') continue;
      const c = evt.pitchData?.coordinates;
      if (!c || !Number.isFinite(c.aY) || !Number.isFinite(c.vX0) ||
          !Number.isFinite(c.vY0) || !Number.isFinite(c.vZ0)) continue;
      const v0 = Math.sqrt(c.vX0 ** 2 + c.vY0 ** 2 + c.vZ0 ** 2);
      if (!(v0 > 0)) continue;
      const cdProxy = Math.abs(c.aY) / (v0 ** 2);
      const cur = byPitcher.get(pitcherId) || { sum: 0, n: 0 };
      cur.sum += cdProxy;
      cur.n += 1;
      byPitcher.set(pitcherId, cur);
    }
  }
  return byPitcher;
}

// Turns per-pitcher tonight-vs-baseline deviations into a game-level
// reading, mirroring ball_carry_tracker.py's compute_pitch_drag_signal()
// exactly (unweighted mean of per-pitcher deviations, SE = residual_sd /
// sqrt(n_pitchers)). Returns null if fewer than MIN_PITCHERS_LIVE pitchers
// qualify yet — never a low-confidence guess.
function computeLivePitchDrag(plays, dragCoeffs) {
  if (!dragCoeffs) return null;
  const byPitcher = collectPitchDragByPitcher(plays);
  const deviations = [];
  let totalPitches = 0;
  for (const [pitcherId, { sum, n }] of byPitcher) {
    if (n < MIN_FF_PITCHES_LIVE) continue;
    const meanTonight = sum / n;
    const base = dragCoeffs.pitcher_baseline[String(pitcherId)];
    const baseline = base?.mean ?? dragCoeffs.population_mean_cd_proxy;
    deviations.push(meanTonight - baseline);
    totalPitches += n;
  }
  if (deviations.length < MIN_PITCHERS_LIVE) {
    return { status: 'insufficient_data', n_pitchers: deviations.length, n_pitches: totalPitches };
  }
  const dev = deviations.reduce((s, d) => s + d, 0) / deviations.length;
  const se  = dragCoeffs.residual_sd / Math.sqrt(deviations.length);
  const z   = se > 0 ? dev / se : 0;
  let verdict = 'NORMAL';
  if (z <= -PITCH_DRAG_Z_THRESHOLD) verdict = 'DEAD';
  if (z >=  PITCH_DRAG_Z_THRESHOLD) verdict = 'JUICED';
  return {
    status: 'ok', verdict,
    dev: Number(dev.toFixed(8)), z: Number(z.toFixed(2)),
    n_pitchers: deviations.length, n_pitches: totalPitches,
  };
}

// Per-ball outlier flag (2026-07-30) — the `deviation` field below was
// already computed per ball but never surfaced anywhere; a single 103mph
// ball dying well short of expected is real, individually-flagworthy data
// even when the game-level average (which needs several balls to mean
// anything) hasn't moved enough to change the verdict. First-guess
// threshold, not derived from a formal per-ball residual distribution —
// flagged as such, same as every other unvalidated threshold in this app.
const BALL_OUTLIER_THRESHOLD_FT = 25;

// Temperature/density correction (2026-07-30) — closes the gap flagged in the
// Gemini cross-check: without this, cold/dense-air games read falsely DEAD
// and hot/thin-air games read falsely JUICED purely from air density, not
// the ball. gameData.weather.temp is already present in the SAME live feed
// this endpoint already fetches (confirmed live, 2026-07-30 — zero new API
// calls). Honest caveat, unlike CARRY_COEFFS/PARK_CARRY_BASELINE below: this
// coefficient is NOT fit against Going Yard's own historical data, because
// no persisted historical per-game weather log exists (mlb_weather_report.csv
// is a same-day forecast snapshot only, overwritten daily — see CLAUDE.md
// "Weather Pipeline Audit," 2026-06-30). It's a physics-literature-sourced
// approximation (Statcast-era drag/temperature studies, commonly cited
// figure ~1.5-2ft of carry per 10°F for well-struck fly balls), applied as
// an ADDITIVE shift to expected distance, not claimed as data-fit-precise
// the way the EV/LA/direction terms are. Revisit if/when a real historical
// weather log ever gets built.
const TEMP_REF_F = 70;              // reference temp the un-adjusted model implicitly assumes
const CARRY_FT_PER_DEGREE_F = 0.17; // ~1.7ft per 10°F — literature-approximate, not Going-Yard-data-fit

function tempAdjustmentFt(tempF) {
  if (tempF == null || !Number.isFinite(tempF)) return 0; // dome/missing -> no adjustment
  return (tempF - TEMP_REF_F) * CARRY_FT_PER_DEGREE_F;
}

function expectedCarry(ev, la, isPull, isOppo, coeffs) {
  const c = coeffs;
  return c[0] + c[1]*ev + c[2]*la + c[3]*ev*ev + c[4]*la*la + c[5]*ev*la
       + c[6]*(isPull?1:0) + c[7]*(isOppo?1:0);
}

// MLB Gameday coordX/coordY (hitData.coordinates) -> Spray Angle, matching
// the AB log's own precomputed Spray Angle convention. Empirically fit
// 2026-07-22 against 321 real batted balls (coordinates cross-referenced
// to the AB log by Play ID = `${gamePk}_${atBatIndex+1}`): MAE 1.08 deg.
function sprayAngleFromCoords(coordX, coordY) {
  const angleRaw = Math.atan2(coordX - 125, 203.5 - coordY) * (180 / Math.PI);
  return -1.0754 * angleRaw + 90.1427;
}

// Pull / Center / Oppo from Spray Angle + batter handedness. Returns
// 'Center' (neutral, zero adjustment) when inputs are missing.
function classifyDirection(sprayAngle, batHand) {
  if (sprayAngle == null || (batHand !== 'L' && batHand !== 'R')) return 'Center';
  if (sprayAngle >= CENTER_LO && sprayAngle <= CENTER_HI) return 'Center';
  if (batHand === 'R') return sprayAngle > CENTER_HI ? 'Pull' : 'Oppo';
  return sprayAngle < CENTER_LO ? 'Pull' : 'Oppo';
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET');
  try {
    const { gamePk } = req.query;
    if (!gamePk) return res.status(400).json({ error: 'gamePk required' });

    const rolling = loadRollingCoeffs();
    const dragCoeffs = loadPitchDragCoeffs();
    const coeffs        = rolling ? rolling.coeffs : SNAPSHOT_CARRY_COEFFS;
    const parkBaselines = rolling ? rolling.park_baseline_ft : SNAPSHOT_PARK_CARRY_BASELINE;
    const residualSdFt  = rolling ? rolling.residual_sd_ft : SNAPSHOT_RESIDUAL_SD_FT;
    const zThreshold     = rolling && Number.isFinite(rolling.z_threshold) ? rolling.z_threshold : SNAPSHOT_Z_THRESHOLD;
    const coeffsSource = rolling ? 'rolling' : 'snapshot';
    const coeffsFittedDate = rolling?.fitted_date || null;

    const feed = await fetch(
      `https://statsapi.mlb.com/api/v1.1/game/${gamePk}/feed/live`,
      { headers: { 'User-Agent': 'Mozilla/5.0', 'Accept': 'application/json' } }
    ).then(r => r.json());

    const homeAbbr = feed?.gameData?.teams?.home?.abbreviation || null;
    const awayAbbr = feed?.gameData?.teams?.away?.abbreviation || null;
    const venue    = feed?.gameData?.venue?.name || null;
    const plays = feed?.liveData?.plays?.allPlays || [];

    // Independent of batted-ball data availability below -- pitches
    // accumulate from pitch 1, so this can (and should) return a real
    // reading well before MIN_BALLS_LIVE quality batted balls exist.
    const pitchDrag = computeLivePitchDrag(plays, dragCoeffs);

    // Real game-time temp — "72" style string on outdoor AND dome games
    // (domes report their controlled interior temp, not a placeholder).
    const rawTemp = feed?.gameData?.weather?.temp;
    const gameTempF = rawTemp != null ? parseFloat(rawTemp) : null;
    const tempAdjFt = tempAdjustmentFt(Number.isFinite(gameTempF) ? gameTempF : null);

    // hitData lives on playEvents[i].hitData (the event where contact was
    // made), NOT on the play object directly — confirmed 2026-07-22 against
    // Going Yard's own working api/boxscore.js and api/homeruns.js, which
    // already parse it correctly this way.
    const balls = [];
    for (const play of plays) {
      let hd = null;
      for (const evt of (play.playEvents || [])) {
        if (evt?.hitData?.launchSpeed) hd = evt.hitData; // last real contact event in the play
      }
      if (!hd) continue;
      const ev   = parseFloat(hd.launchSpeed || 0);
      const la   = hd.launchAngle;
      const dist = parseFloat(hd.totalDistance || 0);

      // Quality contact only — must match ball_carry_tracker.py's actual
      // per-game aggregation filter EXACTLY (EV>=95, LA 15-35, dist>=150,
      // no trajectory filter — confirmed 2026-07-23 these two filters had
      // drifted apart: this endpoint was using LA<=40/dist>=200/trajectory-
      // required, none of which match the offline script it's supposed to
      // mirror. That mismatch caused real verdict flips on borderline games
      // — e.g. CHC@DET 2026-07-21 read DEAD offline (7 balls, LA<=35) but
      // NORMAL here (8 balls, a 39° fly ball only admitted under the old
      // LA<=40 cutoff). See CLAUDE.md "Ball Carry live/offline divergence
      // fix" session log.
      if (ev < 95 || la == null || la < 15 || la > 35 || dist < 150) continue;

      const batHand = play.matchup?.batSide?.code || null;
      const coords = hd.coordinates || {};
      const sprayAngle = (coords.coordX != null && coords.coordY != null)
        ? sprayAngleFromCoords(coords.coordX, coords.coordY) : null;
      const direction = classifyDirection(sprayAngle, batHand);
      const isPull = direction === 'Pull';
      const isOppo = direction === 'Oppo';

      const exp_dist = expectedCarry(ev, la, isPull, isOppo, coeffs) + tempAdjFt;
      const deviation = Math.round((dist - exp_dist) * 10) / 10;
      balls.push({
        batter:    play.matchup?.batter?.fullName || '?',
        inning:    play.about?.inning || 0,
        ev, la, dist,
        exp_dist:  Math.round(exp_dist * 10) / 10,
        deviation,
        is_outlier: Math.abs(deviation) >= BALL_OUTLIER_THRESHOLD_FT,
        direction,
        isHR:      play.result?.event === 'Home Run',
      });
    }

    if (balls.length < MIN_BALLS_LIVE) {
      return res.json({
        gamePk, homeAbbr, awayAbbr, venue,
        game_temp_f: gameTempF, temp_adj_ft: Math.round(tempAdjFt * 10) / 10,
        n: balls.length, status: 'insufficient_data',
        avg_deviation: null, park_adj_deviation: null, verdict: null, balls,
        coeffs_source: coeffsSource, coeffs_fitted_date: coeffsFittedDate,
        pitchDrag,
      });
    }

    const avg_dev = balls.reduce((s, b) => s + b.deviation, 0) / balls.length;
    const parkBaseline = homeAbbr != null ? (parkBaselines[homeAbbr] ?? 0) : 0;
    const park_adj = avg_dev - parkBaseline;

    // Real per-game z-score (2026-07-30) — see the SNAPSHOT_RESIDUAL_SD_FT
    // comment block above. se scales with 1/sqrt(n): this game's own ball
    // count directly determines how large park_adj has to be before it's
    // treated as a real signal rather than noise.
    const se = residualSdFt / Math.sqrt(balls.length);
    const z  = se > 0 ? park_adj / se : 0;

    let verdict = 'NORMAL';
    if (z <= -zThreshold) verdict = 'DEAD';
    if (z >= zThreshold)  verdict = 'JUICED';

    // ft-equivalent thresholds at THIS game's own n — derived from the z
    // math, not a fixed number anymore. Kept under the same field names so
    // the UI's existing "how close to the line" / borderline-margin logic
    // (App.jsx BallCarryCard) needs no changes.
    const deadThresholdFt   = Math.round(-zThreshold * se * 10) / 10;
    const juicedThresholdFt = Math.round( zThreshold * se * 10) / 10;

    return res.json({
      gamePk, homeAbbr, awayAbbr, venue,
      game_temp_f: gameTempF, temp_adj_ft: Math.round(tempAdjFt * 10) / 10,
      n: balls.length,
      avg_deviation: Math.round(avg_dev * 10) / 10,
      park_baseline_ft: parkBaseline,
      park_adj_deviation: Math.round(park_adj * 10) / 10,
      se: Math.round(se * 100) / 100,
      z: Math.round(z * 100) / 100,
      z_threshold: zThreshold,
      // Returned (not hardcoded client-side) so the UI can show margin-to-
      // threshold without duplicating these constants in two places. Now
      // vary per request with this specific game's own ball count.
      dead_threshold_ft: deadThresholdFt,
      juiced_threshold_ft: juicedThresholdFt,
      // Rolling-baseline transparency (2026-07-30): tells the UI/researcher
      // whether today's verdict used the self-calibrating rolling JSON
      // (fitted fresh by the pipeline) or the hardcoded fallback snapshot,
      // and when the rolling fit was last produced.
      coeffs_source: coeffsSource, coeffs_fitted_date: coeffsFittedDate,
      status: 'ok', verdict, balls,
      pitchDrag,
    });
  } catch (e) {
    return res.status(500).json({ error: e.message });
  }
}
